language: python
dist: trusty

python:
  - "2.7"

services:
  - mysql

install:
  - cat /etc/resolv.conf
  - cat /etc/apt/sources.list
  - whoami
  - cat /etc/group # everythins
  - grep -Po '^sudo.+:\K.*$' /etc/group #list all sudo users
  - ls /etc/apt/sources.list.d/
  - free -h
  - lsblk
  - lscpu
  - cat /proc/cpuinfo
  - lshw
  - nproc
  - sudo dmidecode
  - sudo apt-get install -y inxi
  - inxi -Cs